#include "parser.h"
#include <stdio.h>
#include <stdlib.h>
#include "parser.tab.h" // Include the header file generated by Bison

int yyparse(void);
// Declare the root of the AST
ast_node *root;

// Function to create a new AST node for an integer
ast_node *new_int_node(int value) {
    ast_node *node = malloc(sizeof(ast_node));
    node->type = NODE_INT;
    node->data.int_value = value;
    return node;
}

// Function to create a new AST node for an identifier
ast_node *new_identifier_node(char *identifier) {
    ast_node *node = malloc(sizeof(ast_node));
    node->type = NODE_IDENTIFIER;
    node->data.identifier = identifier;
    return node;
}

// Function to create a new AST node for a binary operation
ast_node *new_binary_op_node(ast_node *left, ast_node *right, int op) {
    ast_node *node = malloc(sizeof(ast_node));
    node->type = NODE_BINARY_OP;
    node->data.binary_op.left = left;
    node->data.binary_op.right = right;
    node->data.binary_op.op = op;
    return node;
}

// Function to create a new AST node for an assignment
ast_node *new_assignment_node(char *identifier, int value) {
    ast_node *node = malloc(sizeof(ast_node));
    node->type = NODE_ASSIGNMENT;
    node->data.assignment.identifier = identifier;
    node->data.assignment.value = value;
    return node;
}

// Function to free the AST
void free_ast(ast_node *node) {
    if (node == NULL) return;
    if (node->type == NODE_BINARY_OP) {
        free_ast(node->data.binary_op.left);
        free_ast(node->data.binary_op.right);
    }
    free(node);
}

// Function to evaluate the AST
int evaluate_ast(ast_node *node) {
    if (node == NULL) return 0;
    switch (node->type) {
        case NODE_INT:
            return node->data.int_value;
        case NODE_BINARY_OP:
            switch (node->data.binary_op.op) {
                case PLUS:
                    return evaluate_ast(node->data.binary_op.left) + evaluate_ast(node->data.binary_op.right);
                case MINUS:
                    return evaluate_ast(node->data.binary_op.left) - evaluate_ast(node->data.binary_op.right);
                case ASTERISK:
                    return evaluate_ast(node->data.binary_op.left) * evaluate_ast(node->data.binary_op.right);
                case SLASH:
                    return evaluate_ast(node->data.binary_op.left) / evaluate_ast(node->data.binary_op.right);
                default:
                    fprintf(stderr, "Unknown binary operator\n");
                    return 0;
            }
        case NODE_ASSIGNMENT:
            printf("Assignment: %s = %d\n", node->data.assignment.identifier, node->data.assignment.value);
            return node->data.assignment.value;
        default:
            fprintf(stderr, "Unknown node type\n");
            return 0;
    }
}


